@url_dev=http://localhost:3058/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type:application/json
x-api-key:eb08125dd18fb7d7f4084d3a48913be0eb980098b9689e18f96b9ab010c4143f91fcaa416ec8a5a92ab1a3021686f710aa7284ec60e2cd1ef549319ce291b5f9
{
    "name": "abc",
    "email": "shoptipjs45@gmail.com",
    "password": "123aaa"
}

### login
POST {{url_dev}}/shop/login
Content-Type:application/json
x-api-key:e9e70d7ea217b2c95097dcf5abb8c4f38597d5d70507b90ce67b8aeab97252c192cad97c75d7bb2ced81ffadc37ddbeeb0b3712c3960f740a51ab0ca6361c1c8
{
    "email": "shoptipjs45@gmail.com",
    "password": "123aaa"
}


### logout
POST {{url_dev}}/shop/logout
Content-Type:application/json
x-api-key:8f183b32e6fb7c870fd5e967f61dfcf91ff4331e758ab71e37b93f3a1e78709375827893d2a24e737164771dad8458230b1b75cd691627e823ddf447f4c6ca37
x-client-id:695f86ded9159fcd3b5d7d14
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTVmODZkZWQ5MTU5ZmNkM2I1ZDdkMTQiLCJlbWFpbCI6InNob3B0aXBqczQzQGdtYWlsLmNvbSIsImlhdCI6MTc2NzkyODU0NiwiZXhwIjoxNzY4MTAxMzQ2fQ.Zz-FjNom8QLWSJ1PcCaY5xIEvzxXk-eCsZSlxlE-vcHRWLZsnSVIrmx1cdN-WmIqGyJ_j3X7huc4a9fUKetsf_rune_uraqS27lUrx2jYC2WmgFmI41iEemEv9VYtmdT_TOVhsj8yedmtDR9jMXTPCMkXt2sKErYvXGMDcCzzkBV__xx572E4ZlkkH6G2M9nwrPXERn55EMabFDmoDuM8GRFco6wsQHLoIp8RynGLoo0Tx0TAsuor0oHQeWEPMAyy53169XyKnC98vqoy9aH213_jz_nFF_R3kyTharh7XIWys-HCKMGkmp-319yiKNO9Nc_e_3LtRh2cwB1Vtrz3NmHuWyFJkDRBRihlDA71E8tKoxWhSK_NihyooJW38fOWqYISHo9DsfO-VNsso1SB0DgrjKidVVsMU6s-J3tvsg_18BEZsYvR6mNPECIaI0VBQO3-TxpG0yUQssGqe_bj2ypHEtdKx1ImbXffuYeK7aLnQq6pyVLUgdt2ksBjQ0EI0gbA6M4s0f-gGNLqJEujzwR7zAXVMEOhMJfRZZBYKEp_by-U1Pu_tQuReJ8ay5P1KzzLDkUnN_W6YPrmHe4pW6vEqwcACbIZObuIslTcYHZh3n8hX1Dpm5Af4G_eP0kB-PhzlX49PYh-6wk3HFGXwqSFb_i5kBUtjRZSyK9ySI


### refreshToken
POST {{url_dev}}/shop/refreshToken
Content-Type:application/json
x-api-key:c5d05a3f3368f1de125e7557fe1e54c45402540d8b12c20070df7c73f8dfbeec9eb21650b6a0293baf86b320d156261fd93942f21d381ec4360f933051e5d970
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODEzNjk1MSwiZXhwIjoxNzY4MzA5NzUxfQ.dGrYQAOmcT-61cNtTQpfBEDHepmvO-_icvXykxADUt15C0pnH540pzs3u1RVNHOaSBQ-Ni9YMFtfehNYRsXP-RCnPtwGeeBXV_JLA5cfXWBJ-Py7KLpWU1fenLW8bwgjmt8fDzQe5r7wCM1M10XmIqtWw_9UdhpjpZ3xHbmf4lZlFXBzPCaocOrYXkaWDUrXZc56Xtbr_2Zv9qwcspfd1nlyGYE_W9QXLJlCbDWbF-ZjBzH-bINH02kvDRauPkOiwJnwjjUO00Wiw5cOqvVg67DzbZH1XlrHxTk8-gtgIARJUFdHiUg_FvIplN5Epj_IrHhQeoa3X6ystQ3cX_oIo_FEVytaQNGNWUNVbCNBDGcBH1HDt-iYf7JpjR6vlAPwvS26Pgsl7GOsaDTZk0sML-6s2_JLLmKsNQDKu8Xds23NyNKXjx7AiwH-50zmr48X75AyD_-HAjKSxXTv61aJ3CgGP2mqtoGVzDfvgQI9ng8HCxCFmaBZ_sGrvzwqyj2DFCKvPh7szdAfXxpaGulwDfOv4Vq0hZNnfoSDCB7tdJBi67pBr6NTwB8NEEYum3qjDRDjYzdJn9FhZlePEvbhPGjJfgbC7jTmlmhssTtaUtloac8kX4I0Ij69_8NXNB3hl3RJkzLd100ZKtZRHV1ZfvqFHznRYlb3xfaesPw76JI
{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODEzNjk1MSwiZXhwIjoxNzY4NzQxNzUxfQ.epL799ghG6zML_L3hirWvtnOd1kAh5OjyeyLZfIMVL_TCaCQ3a1aaY6yROMs3Kt_8WPG2_89YEPt8Q5lVKzPzQtHO6v09rAaF7gFHhz1YavPHtn_b30qjhTzkyjkeeza27WryboM4VtkTqIXWd1XrVPaEB4XjXu7uOFtcY98x2x9HdfMBzmkeOacXeC18df5xG3nkrWUyT3wu438_R-ph8FZ-n_2NOEFXrClcBcd1Q_RaDGr81eg-xOcyUVyypGsk7l_Bzl8-sL44CgfX1PciEwxD-WMUUspQVXghXpxpl1derK20VoxVj8YeRqsLoCYA5mX6zDVRKEwUm3YVPid0H7TATk3QrpeYHu3T1SaubXxKkHl1dwZMh95dIXxm_Hu5UXgpPNsZwW9Y2pRVcGEyk36sPla4KDssTy4GyDgM04Km2nnDY3NiDeWuKc-7VH9y8SkABTddA5wsmfntQgXfgxvO3XKsGX_ilAJNrsPSCCwpXwdXncb4XP3PoCOYZrYeyQm53vNMv8fapIqICjzH3LtbZrnF2vw9i6loWfRj9dGqtJkPYqa9K5Q66GJH-gcJsIkoaabU00zrqbMDcq4F3uAZgUP0Yoi35rMtnv08CDnjWB7Ki4ZZZufR3CeTl3kyJhPSeKaOTzz5nqYFFk3Ah5VQ9ire0sMds1YSWBwnEw"
}
