@url_dev=http://localhost:3058/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type:application/json
x-api-key:b19ac139cbf08794a6428c4dbf6dcc437e9259adaaa68a63cebab92151ca720c7dae4b35ca74c6c49dfc54005af76bbe589915019ab92492ea5d5b9ea9d2cef1
{
    "name": "abc",
    "email": "shoptipjs43@gmail.com",
    "password": "123aaa"
}

### login
POST {{url_dev}}/shop/login
Content-Type:application/json
x-api-key:b19ac139cbf08794a6428c4dbf6dcc437e9259adaaa68a63cebab92151ca720c7dae4b35ca74c6c49dfc54005af76bbe589915019ab92492ea5d5b9ea9d2cef1
{
    "email": "shoptipjs43@gmail.com",
    "password": "123aaa"
}


### logout
POST {{url_dev}}/shop/logout
Content-Type:application/json
x-api-key:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTVmNmU3ZmViYWI3M2M1YjcxMmU4NzMiLCJlbWFpbCI6InNob3B0aXBqczQzQGdtYWlsLmNvbSIsImlhdCI6MTc2Nzg2NzQyMiwiZXhwIjoxNzY4MDQwMjIyfQ.Zt-G2HRaToD8qJ8ARilE2AJDbCInYcxo8or6N6Tm1ISrIPjOuz13mrEMSXvUg5tqSs3CDR7UqW-pueSF2NiD4rCmJyfBsIGg7rH3Vy4Qcn8_cMGjrBQvyDYTjgJdFrCdrDQSFLw7vroPBFrX6zGmLMZwuE98OrHfXtKz9Fg--wXjd5l9qRGg0vU1ekMnDYdH-09pEEeZJydtAn_uY7Uo3l7Vgb6YJ5GRIhAlBryMGhaNsJBF9E0halSJR8ersGn4p99F_9YwyqyyE5r1lSYEv1LzF5_yX6cQlSJnes7QsyJP95xgbGrosTY2sZAXwciFCV7ylWoVP50XYYqMhEUAL3-_WirRBZ0VrduJo27lovAInDTgkrd2QxtdrIpHLVqU7B0MRGh1sesyLqECGdES6G8kWaiU3TrQJP8w_mPxBl1MLSXtVu9wWKjHoHbQaK69O7iAmgcmwC--G8UDXjwvIz_g4BYXPG_nKPrCdo5Gg3tfvDx79HHbujcAvvl3BTrUngSrwlDd70Z6Bpld14TeYD_gcfh2OiEVJ79GK8IqkD9hGASSQ44zqiPhrzq80Dfd_bosqtUjfPrNv2y8X5_3OuHLyWZtBc60eZJ_UBG2Ee20ZBVtnqiAwhWiTndhR-xx3f5CjYJdl2asLPV9W8XzZD4ex720NFF6acHmBIlzs44
x-client-id:695f7463f457bf7739f0347d
{
    "email": "shoptipjs43@gmail.com",
    "password": "123aaa"
}