@url_dev=http://localhost:3058/v1/api

### signup

### login
POST {{url_dev}}/shop/login
Content-Type:application/json
x-api-key:e02d76c018582571fac45bc81c2fc66ef2d0e552809f75b32616b43a361e6dc102e2e5877b36019ba91c84c33dd00fc07ed2e76390110a5a5f1ba7118d1f5633
{
    "email": "shoptipjs45@gmail.com",
    "password": "123aaa"
}


### product
POST {{url_dev}}/product
Content-Type:application/json
x-api-key:6c6d994aa6ee24309b232399ad7feded29e62759c90a90df708552258cbea474f95f24e8f53e1f8008850ae6c0972e1b61b08e015e843a7ba1a441c3b7e71d60
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2OTMxMDE5NCwiZXhwIjoxNzY5NDgyOTk0fQ.DyPNxuUnTfH_6LYWCyRFrCr9roK0IqFRkOWnXDr8FxkB68RjcilxEucGXmIPMMGRokFIm9TsEQYrCoMllBzSWSapEZ1Gu_fBtDN7bS6AOCididatlxJauzZpHFaB_YRlKPNqBBe87ahG4DCGOvNdzRlFJALAJVZV5BmMigEk-Re5C-F-3dtUDqhR5w1DVBUMGM6CsO76-cXrNRZye6hLfsxdU9niryk5cL_vFNHQFAB11qo96fBMT-G0lch9rg5m9QN4rhpHreePnEu6iXDYDrTqBtPVEWxd0yopOh_MJcCxLFtLpwglMVcyc2_MACEmYISI1DeaZEFPpr_mx--_iuZnWwgdGdDLKGGpVBlpITXzA5eAeyUtfx0-1fFXNGTZho7Rr38GfOokDcvzDWbr_huG_jBlU28U7IQpvnGTMXiTzUJ7rnBk_sc1DqgpEik6gLPldorKr74BrUKQpUbQU3-ptsbFMUAyS-lLx71FpV5AyKAHlvyO3NOGGx3zDbODk6FJit_EoeArJc5cu6Numcv5nYWobMY7TfJ1xixAOf8o8Q9IcWz7w5i3joeA9Qi8sXVtLEeHHL1GhnIiKaKPJlskq8KGSkYUMofjaJC5Jx3or3PbLUCThJQTzY0ZMh1FcPmcYKkNKMeb5cMPFmJ1ifOlbVrGZiZKTmYtFPobzvs
{
    "product_name":"Sản phẩm 3 test",
    "product_description":"Mô tả",
    "product_thumb":"product thumb",
    "product_price":500000,
    "product_quantity":18,
    "product_type":"Clothing",
    "product_attributes":{
        "brand":"Others",
        "size":"XLL",
        "material":"Nhựa, silicon, TPU"
    }
}


### product list drafts
GET {{url_dev}}/product/draft/all
Content-Type:application/json
x-api-key:4269b1eb6132e87b0f1351d76697f39fb58c860c6ae35f17e8f75e4ace9a78f2d697c76ce179ea7b91a1626f02d2789537f55de9068e8764da4a1eb63552c4da
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDQyNiwiZXhwIjoxNzY5MDA3MjI2fQ.ekYWZV37ugGQX7n1K8HKhYFXfal7C6ccbYJwEyMarybOzkH44tjf98TQbq-4tHiDdffHYFuRDr2OoxD4p-pK63TT49tj_-tR7R_3gCTHwGTeX9Rr_1Lwo_pJqUr3Bg0McSXTvPF9MvBzb9K9497gLwLx8V6v3stRReFil3xPL-tLLKbv3TniiFH0hwwdo5CwvQeQcCszWwkaEESm_zVKB6_b34SwMYMqhlInVtuN1Rn2_4jO3RWKMtP8kKYQPvzo2HY4CsxVOsKtVwsl9t5qIJMdCZAd89bbJOS0AYUrrqC3H2a4OimixG8pOtzJYiIHIzz55TD16xHbB56wMyN0WaslIbZIWHWspJeLLV-Uyq_NL8oIWDU2zlcXm_QipgGncQHZhAdUf85zhYqL_pqF5JL6u9rjuZQ_krz3kP1OKp2ZCcO7aOxmBhhkGWk7Qs2KS4z51eAZeafTFpS_MUMgIirIixKbmN86e8cXWc_Zao9X_BNtNb7z4i6_QxCat7o20CWjtp9LFkUg821pDlA3Ghk-6RbE9LMriUCVDHcEOgesNQIDv6fX6wR4XBnIoZynXlx0T9qxITXZaTIOboy0zaH8SofFVJ0s0TU33rfhij_-pPV1xXF55DDRhX_7ehxoSxPqHhIp5pOTI4QX3fve6BX3WacCxw2ZVZVj_aHn3vs


### product get all published
GET {{url_dev}}/product/published/all
Content-Type:application/json
x-api-key:4269b1eb6132e87b0f1351d76697f39fb58c860c6ae35f17e8f75e4ace9a78f2d697c76ce179ea7b91a1626f02d2789537f55de9068e8764da4a1eb63552c4da
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDQyNiwiZXhwIjoxNzY5MDA3MjI2fQ.ekYWZV37ugGQX7n1K8HKhYFXfal7C6ccbYJwEyMarybOzkH44tjf98TQbq-4tHiDdffHYFuRDr2OoxD4p-pK63TT49tj_-tR7R_3gCTHwGTeX9Rr_1Lwo_pJqUr3Bg0McSXTvPF9MvBzb9K9497gLwLx8V6v3stRReFil3xPL-tLLKbv3TniiFH0hwwdo5CwvQeQcCszWwkaEESm_zVKB6_b34SwMYMqhlInVtuN1Rn2_4jO3RWKMtP8kKYQPvzo2HY4CsxVOsKtVwsl9t5qIJMdCZAd89bbJOS0AYUrrqC3H2a4OimixG8pOtzJYiIHIzz55TD16xHbB56wMyN0WaslIbZIWHWspJeLLV-Uyq_NL8oIWDU2zlcXm_QipgGncQHZhAdUf85zhYqL_pqF5JL6u9rjuZQ_krz3kP1OKp2ZCcO7aOxmBhhkGWk7Qs2KS4z51eAZeafTFpS_MUMgIirIixKbmN86e8cXWc_Zao9X_BNtNb7z4i6_QxCat7o20CWjtp9LFkUg821pDlA3Ghk-6RbE9LMriUCVDHcEOgesNQIDv6fX6wR4XBnIoZynXlx0T9qxITXZaTIOboy0zaH8SofFVJ0s0TU33rfhij_-pPV1xXF55DDRhX_7ehxoSxPqHhIp5pOTI4QX3fve6BX3WacCxw2ZVZVj_aHn3vs


### product published
POST {{url_dev}}/product/publish/696e45b70600d1de363c416e
Content-Type:application/json
x-api-key:4269b1eb6132e87b0f1351d76697f39fb58c860c6ae35f17e8f75e4ace9a78f2d697c76ce179ea7b91a1626f02d2789537f55de9068e8764da4a1eb63552c4da
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDQyNiwiZXhwIjoxNzY5MDA3MjI2fQ.ekYWZV37ugGQX7n1K8HKhYFXfal7C6ccbYJwEyMarybOzkH44tjf98TQbq-4tHiDdffHYFuRDr2OoxD4p-pK63TT49tj_-tR7R_3gCTHwGTeX9Rr_1Lwo_pJqUr3Bg0McSXTvPF9MvBzb9K9497gLwLx8V6v3stRReFil3xPL-tLLKbv3TniiFH0hwwdo5CwvQeQcCszWwkaEESm_zVKB6_b34SwMYMqhlInVtuN1Rn2_4jO3RWKMtP8kKYQPvzo2HY4CsxVOsKtVwsl9t5qIJMdCZAd89bbJOS0AYUrrqC3H2a4OimixG8pOtzJYiIHIzz55TD16xHbB56wMyN0WaslIbZIWHWspJeLLV-Uyq_NL8oIWDU2zlcXm_QipgGncQHZhAdUf85zhYqL_pqF5JL6u9rjuZQ_krz3kP1OKp2ZCcO7aOxmBhhkGWk7Qs2KS4z51eAZeafTFpS_MUMgIirIixKbmN86e8cXWc_Zao9X_BNtNb7z4i6_QxCat7o20CWjtp9LFkUg821pDlA3Ghk-6RbE9LMriUCVDHcEOgesNQIDv6fX6wR4XBnIoZynXlx0T9qxITXZaTIOboy0zaH8SofFVJ0s0TU33rfhij_-pPV1xXF55DDRhX_7ehxoSxPqHhIp5pOTI4QX3fve6BX3WacCxw2ZVZVj_aHn3vs

### product unPublished
POST {{url_dev}}/product/unpublish/696a04b030bd2c536e788f1c
Content-Type:application/json
x-api-key:e02d76c018582571fac45bc81c2fc66ef2d0e552809f75b32616b43a361e6dc102e2e5877b36019ba91c84c33dd00fc07ed2e76390110a5a5f1ba7118d1f5633
x-client-id:696e44950600d1de363c4128
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDE5OCwiZXhwIjoxNzY5MDA2OTk4fQ.RTCNPnFPndy0R-ncPQmHJgqhGxGRikM9oh0xbNgSdz1Tpp9TvISZahyqI67oR4X_SGr3Dku3RGwxJn6GbURTenUbdTSZ4OkP5R34VJT_MjbAr-z86X2e7WPQJnwflK1Wf_xqqlF-IZA1krbCIAoOadM5wDUJTw2op2HXcV6siux6VFeamR152QurGS7JysQ15amOSWI15zyeO2v-zpvjzRGNE9XUal31KTVbpmSMgtwT_GecT5e5k4swAPOckZ3LXNAj4dadREb5bOLouxw3SXPhtkt86C_CAEU8vdOYEZQa9dkwhBMWnQCkIHsfit00IFIUaz9bHYQceUFi45i_94jqRyt2d2XnhyfDDQFl4hAQuPakQJxWHtqBef-kCJNtBo14KiBq6P-QriEPUtVJTjEDd0h7Y1P9TQwRa9klPB-MB8OR72VnKeB26-mZyomokfiIlnOTR8wGdKkbHHx5QJIdkaecpGowdBgTzY7aOUezh3Xi_Dpw2pUYmOvxSfJ0B0iCxy1S6zc4Ek-LhA0QE_m5UdwJv9qDn7PLgec8QzReLrXn8uMyqBkjYNqgnZZ21cGOyczyHpm_I9K_g0eDSMJnAav9DzZXuQAjxTJ5lMmObsOWgXfqR16VnG6XFoeXML4xVYu-tczSjHgqbmbWz1FJ2fr1KIk4_etWYm4vdyM




### get list search product
GET {{url_dev}}/product/search/san
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68



### get list all product by user
GET {{url_dev}}/product
Content-Type:application/json
x-api-key:4269b1eb6132e87b0f1351d76697f39fb58c860c6ae35f17e8f75e4ace9a78f2d697c76ce179ea7b91a1626f02d2789537f55de9068e8764da4a1eb63552c4da
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDQyNiwiZXhwIjoxNzY5MDA3MjI2fQ.ekYWZV37ugGQX7n1K8HKhYFXfal7C6ccbYJwEyMarybOzkH44tjf98TQbq-4tHiDdffHYFuRDr2OoxD4p-pK63TT49tj_-tR7R_3gCTHwGTeX9Rr_1Lwo_pJqUr3Bg0McSXTvPF9MvBzb9K9497gLwLx8V6v3stRReFil3xPL-tLLKbv3TniiFH0hwwdo5CwvQeQcCszWwkaEESm_zVKB6_b34SwMYMqhlInVtuN1Rn2_4jO3RWKMtP8kKYQPvzo2HY4CsxVOsKtVwsl9t5qIJMdCZAd89bbJOS0AYUrrqC3H2a4OimixG8pOtzJYiIHIzz55TD16xHbB56wMyN0WaslIbZIWHWspJeLLV-Uyq_NL8oIWDU2zlcXm_QipgGncQHZhAdUf85zhYqL_pqF5JL6u9rjuZQ_krz3kP1OKp2ZCcO7aOxmBhhkGWk7Qs2KS4z51eAZeafTFpS_MUMgIirIixKbmN86e8cXWc_Zao9X_BNtNb7z4i6_QxCat7o20CWjtp9LFkUg821pDlA3Ghk-6RbE9LMriUCVDHcEOgesNQIDv6fX6wR4XBnIoZynXlx0T9qxITXZaTIOboy0zaH8SofFVJ0s0TU33rfhij_-pPV1xXF55DDRhX_7ehxoSxPqHhIp5pOTI4QX3fve6BX3WacCxw2ZVZVj_aHn3vs


### get detail product by user
GET {{url_dev}}/product/696e45b70600d1de363c416e
Content-Type:application/json
x-api-key:4269b1eb6132e87b0f1351d76697f39fb58c860c6ae35f17e8f75e4ace9a78f2d697c76ce179ea7b91a1626f02d2789537f55de9068e8764da4a1eb63552c4da
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODgzNDQyNiwiZXhwIjoxNzY5MDA3MjI2fQ.ekYWZV37ugGQX7n1K8HKhYFXfal7C6ccbYJwEyMarybOzkH44tjf98TQbq-4tHiDdffHYFuRDr2OoxD4p-pK63TT49tj_-tR7R_3gCTHwGTeX9Rr_1Lwo_pJqUr3Bg0McSXTvPF9MvBzb9K9497gLwLx8V6v3stRReFil3xPL-tLLKbv3TniiFH0hwwdo5CwvQeQcCszWwkaEESm_zVKB6_b34SwMYMqhlInVtuN1Rn2_4jO3RWKMtP8kKYQPvzo2HY4CsxVOsKtVwsl9t5qIJMdCZAd89bbJOS0AYUrrqC3H2a4OimixG8pOtzJYiIHIzz55TD16xHbB56wMyN0WaslIbZIWHWspJeLLV-Uyq_NL8oIWDU2zlcXm_QipgGncQHZhAdUf85zhYqL_pqF5JL6u9rjuZQ_krz3kP1OKp2ZCcO7aOxmBhhkGWk7Qs2KS4z51eAZeafTFpS_MUMgIirIixKbmN86e8cXWc_Zao9X_BNtNb7z4i6_QxCat7o20CWjtp9LFkUg821pDlA3Ghk-6RbE9LMriUCVDHcEOgesNQIDv6fX6wR4XBnIoZynXlx0T9qxITXZaTIOboy0zaH8SofFVJ0s0TU33rfhij_-pPV1xXF55DDRhX_7ehxoSxPqHhIp5pOTI4QX3fve6BX3WacCxw2ZVZVj_aHn3vs




### update product
PATCH {{url_dev}}/product/696e45b70600d1de363c416e
Content-Type:application/json
x-api-key:6c6d994aa6ee24309b232399ad7feded29e62759c90a90df708552258cbea474f95f24e8f53e1f8008850ae6c0972e1b61b08e015e843a7ba1a441c3b7e71d60
x-client-id:6963a0aa1c9fccaf14f8b0e6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTYzYTBhYTFjOWZjY2FmMTRmOGIwZTYiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2OTMxMDE5NCwiZXhwIjoxNzY5NDgyOTk0fQ.DyPNxuUnTfH_6LYWCyRFrCr9roK0IqFRkOWnXDr8FxkB68RjcilxEucGXmIPMMGRokFIm9TsEQYrCoMllBzSWSapEZ1Gu_fBtDN7bS6AOCididatlxJauzZpHFaB_YRlKPNqBBe87ahG4DCGOvNdzRlFJALAJVZV5BmMigEk-Re5C-F-3dtUDqhR5w1DVBUMGM6CsO76-cXrNRZye6hLfsxdU9niryk5cL_vFNHQFAB11qo96fBMT-G0lch9rg5m9QN4rhpHreePnEu6iXDYDrTqBtPVEWxd0yopOh_MJcCxLFtLpwglMVcyc2_MACEmYISI1DeaZEFPpr_mx--_iuZnWwgdGdDLKGGpVBlpITXzA5eAeyUtfx0-1fFXNGTZho7Rr38GfOokDcvzDWbr_huG_jBlU28U7IQpvnGTMXiTzUJ7rnBk_sc1DqgpEik6gLPldorKr74BrUKQpUbQU3-ptsbFMUAyS-lLx71FpV5AyKAHlvyO3NOGGx3zDbODk6FJit_EoeArJc5cu6Numcv5nYWobMY7TfJ1xixAOf8o8Q9IcWz7w5i3joeA9Qi8sXVtLEeHHL1GhnIiKaKPJlskq8KGSkYUMofjaJC5Jx3or3PbLUCThJQTzY0ZMh1FcPmcYKkNKMeb5cMPFmJ1ifOlbVrGZiZKTmYtFPobzvs
{
    "product_attributes": {
      "brand": "Iphone 11"
    },
    "product_type": "Clothing",
    "product_quantity": 29
}