@url_dev=http://localhost:3058/v1/api

### signup

### login
POST {{url_dev}}/shop/login
Content-Type:application/json
x-api-key:1566c3f87feee07219c54e078e223976466ae9723ba0ab6a238d838f65d56899f2d91ed3d0d22abeb24276bf99c8b35dc42d8b0171341b5fb278d4a77fe3880f
{
    "email": "shoptipjs45@gmail.com",
    "password": "123aaa"
}


### product
POST {{url_dev}}/product
Content-Type:application/json
x-api-key:9a75385a235a11b9081d9cbf5994d9a0b3b43907382bddfcc9e540513a4905f1d5b82520090e8332b53695ff2c23ab07f3430fe8d8738b32a7761d43c5d873df
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODQ2ODIwMywiZXhwIjoxNzY4NjQxMDAzfQ.UAzQu2z6jXkOTjPx66glMqPnWbyeLNgBjTYMQMOse2ooUFJlp7MOo00BLMFTF9eawvNnhIMJnhWnnke6xiqeelBuxxA7VAvK2tQmgt0KqzTmtTjgU6wP9pldjw_a89-o8euhuCX5d1RgL6H9otjIToiEQwUyttt4Wx9Kpp8PkiwasoL1QwxsllWUcnMCr-FkJ5I4r5AmBaT3J5CcNdKyZoh0D1MyLVIEJfL3HM2rfuwzZkM3PlRqlPb0ZbA0HdqTvs_lTE3Y0C6hTfd7obiWhoKMSP-wfgF0UY0Sw2rNyY9KS7mMcHVLFgE7wNXHq0m3NNUWABMJ4huZWVB2FX9RBO-Z1G9Xe5ArHvWva6O4Q6DusnNqZjeg0KPjZfJK36a1huo9j1_6Xeuu3pAYS80J_gUjr6pfsgEFBtButuGcGOZtTfoAkruEQrqshNzF7qmYABPq8lSUyiJ_bCKdgd6OlTcoVObRvEhPi-Tx6PnWCjUCAlV9MToI0VcI7g8NW3i1pUNxcFmyQy0zXyV2mZZi3w4MCQgl5tBwBhxZX76c7aBFWU_GXpFjrGtstSfZLAtbvJavTp1bSNOZD2w-CqlGNAGm_bVTUgTuc818IrleaRHYwZ8JDcmovGq65supt68pylwT7XRa51xYPAobik5QTFSjG9MsFcP7Yw4zWrdccO0
{
    "product_name":"Iphone 24 promax",
    "product_description":"New product",
    "product_thumb":"product thumb",
    "product_price":20000000,
    "product_quantity":8,
    "product_type":"Electronics",
    "product_attributes":{
        "manufacturer":"Apple 2",
        "model":"iphone 24",
        "color":"BLUE 2"
    }
}
