@url_dev=http://localhost:3058/v1/api

### signup

### login
POST {{url_dev}}/shop/login
Content-Type:application/json
x-api-key:1566c3f87feee07219c54e078e223976466ae9723ba0ab6a238d838f65d56899f2d91ed3d0d22abeb24276bf99c8b35dc42d8b0171341b5fb278d4a77fe3880f
{
    "email": "shoptipjs45@gmail.com",
    "password": "123aaa"
}


### product
POST {{url_dev}}/product
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68
{
    "product_name":"Sản phẩm ok1 ",
    "product_description":"Mô tả",
    "product_thumb":"product thumb",
    "product_price":500000,
    "product_quantity":18,
    "product_type":"Clothing",
    "product_attributes":{
        "brand":"Others",
        "size":"XLL",
        "material":"Nhựa, silicon, TPU"
    }
}


### product list drafts
GET {{url_dev}}/product/draft/all
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68


### product get all published
GET {{url_dev}}/product/published/all
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68




### product published
POST {{url_dev}}/product/publish/696a04b030bd2c536e788f1c
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68


### product unPublished
POST {{url_dev}}/product/unpublish/696a04b030bd2c536e788f1c
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68




### get list search product
GET {{url_dev}}/product/search/san
Content-Type:application/json
x-api-key:5ea47e5ad65ca410d1aa206fe3cea7aece1d59fa23ed556e3319fecc5d3cc746a5272a318bc256335c9724daaa5da54ff9ce55d866a96bb9824842551c565807
x-client-id:696723da11d5ec5851bacb95
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3MjNkYTExZDVlYzU4NTFiYWNiOTUiLCJlbWFpbCI6InNob3B0aXBqczQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODU1NTIxMCwiZXhwIjoxNzY4NzI4MDEwfQ.suMUujtFQwTsxOZUyvVC5GSyzbdOVTbDnGhfWWttSNzqeJiFMbSMQnsFrSnsjnRRJqSzOEAUypvqVJj2ARjNWAKcl7bkVdnO2uo_Tfu3leZbbtE2EXjwpQqQBRArD5anU1NmYheTqWWG5T_bMkVGRfBgC9xAKCwm6RmBtovCuzFfI__kYqRue9DVO5G8jAKhmW41iNbNi-MYdgz8WdlkGOuhWCNazlArr8Nr3_LEgvAWgkFEcD_3AZsgbCLIuZ_4Nw_6dAOehuPF8AbxKcEz-sjhGAzMStJZPNytYmgHgxmm1I8bB8nUgn4uGJbgnMjca000ofWvLcmzkAkqv4UCwLdmyDzEMJAXRTryDGPf7nQ3PaIPVSxEBB5Irza4WxL9stO_Vl7BKkfMWb0HPVTxMyAkg87xC3y6RmQrsfnnuLE-UlZSym0i21CTaTAAr2KogI6vi7niBaIRSFQFpz0nT-KNEt3HUxoMzv6GNbREf765DvACDRcTh7GYvXeGWSwypPyi0Xwmjbd1NZft_h5trxW3aydpqSmUAHLWgO9egycIWb_yv-K14jQOM0nli6-0N4q5nm3QHs35XcWO30WuVAbbEgXQTFp178X4vLYL9FVBwvrDNWp7m6sMT3yW15tNA7s0sWa8EaLr-RfhAITw6cttQSLN8qzGrx_uqY1fG68